export const state = () => ({
    list: [
        {id: 1, title: 'At iam decimum annum in spelunca iacet',previewText: 'An potest cupiditas finiri? Utram tandem linguam nescio',thumbnail: '~/assets/images/tech.jpg', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid, de quo nulla dissensio est? Sed in rebus apertissimis nimium longi sumus. Quid adiuvas? Duo Reges: constructio interrete.'},
        {id: 2, title: 'At iam decimum annum in spelunca iacet',previewText: 'An potest cupiditas finiri? Utram tandem linguam nescio',thumbnail: '~/assets/images/tech.jpg', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid, de quo nulla dissensio est? Sed in rebus apertissimis nimium longi sumus. Quid adiuvas? Duo Reges: constructio interrete.'},
        {id: 3, title: 'At iam decimum annum in spelunca iacet',previewText: 'An potest cupiditas finiri? Utram tandem linguam nescio',thumbnail: '~/assets/images/tech.jpg', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid, de quo nulla dissensio est? Sed in rebus apertissimis nimium longi sumus. Quid adiuvas? Duo Reges: constructio interrete.'},
        {id: 4, title: 'At iam decimum annum in spelunca iacet',previewText: 'An potest cupiditas finiri? Utram tandem linguam nescio',thumbnail: '~/assets/images/tech.jpg', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid, de quo nulla dissensio est? Sed in rebus apertissimis nimium longi sumus. Quid adiuvas? Duo Reges: constructio interrete.'},
        {id: 5, title: 'At iam decimum annum in spelunca iacet',previewText: 'An potest cupiditas finiri? Utram tandem linguam nescio',thumbnail: '~/assets/images/tech.jpg', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid, de quo nulla dissensio est? Sed in rebus apertissimis nimium longi sumus. Quid adiuvas? Duo Reges: constructio interrete.'},
        {id: 6, title: 'At iam decimum annum in spelunca iacet',previewText: 'An potest cupiditas finiri? Utram tandem linguam nescio',thumbnail: '~/assets/images/tech.jpg', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid, de quo nulla dissensio est? Sed in rebus apertissimis nimium longi sumus. Quid adiuvas? Duo Reges: constructio interrete.'},
    ]
});